server:
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/backend-protocol: HTTPS
      nginx.ingress.kubernetes.io/force-ssl-redirect: true
    hosts:
      - argocd.minikube.local
    tls:
      - secretName: argocd-secret
        hosts:
        - argocd.minikube.local
dex:
  enabled: false
redis:
  enabled: false
