apiVersion: v1
kind: Pod
metadata:
  name: training-api
  labels:
    app: api
spec:
  containers:
  - name: training-api
    image: mycloudfun/training-api:1.0
    imagePullPolicy: Always
    volumeMounts:
    - name: data
      mountPath: /data
  initContainers:
  - name: seed-job
    image: yauritux/busybox-curl
    command: ["/bin/sh"]
    args: ["-c", "curl www.onet.pl > /data/website.html"]
    volumeMounts:
    - name: data
      mountPath: /data
  volumes:
  - name: data
    emptyDir: {}
