apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: prometheus-example-monitor
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: prometheus-example
  endpoints:
    - port: 8080
      path: '/metrics'
      interval: 10s
      honorLabels: true
