apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: jenkins-operator-http-training-ingress
spec:
  rules:
  - host: jenkins.minikube.local
    http:
      paths:
      - backend:
          serviceName: jenkins-operator-http-training
          servicePort: 8080

          
