kind: PersistentVolume
apiVersion: v1
metadata:
  name: website-vol
  labels:
    type: local
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/website-vol"

    