kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: website-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  volumeName: website-vol
  resources:
    requests:
      storage: 1Gi