apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: sample-app
  labels:
    name: sample-app
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: sample-app
    spec:
      containers:
      - name: sample-app
        image: mycloudfun/efk-sample-app:1.0
        imagePullPolicy: Always
      restartPolicy: Always
